Step 5
nicolasrll/framework-from-scratch pull request #16
Opened 2020-01-14 17:47 UTC by nicolasrll

#13

2020-01-15 12:11 UTC, fmoy requested changes

2020-01-15 12:11 UTC, fmoy commented on Controllers/AccueilController.php
> +class AccueilController{
Voir norme PSR-12 + PSR 0 et PSR 4 (+ PSR 2 ?)

2020-01-15 12:11 UTC, fmoy commented on _header.php
> +			<li><a href="/see">Accueil</a></li>
tu ne dois pas avoir /see mais / tout cours

2020-01-15 12:11 UTC, fmoy commented on index.php
> +				$controller =  $uri[0];
Tu peux donc récupérer un controller ayant une valeur chaine vide

2020-01-15 12:11 UTC, fmoy commented on index.php
> +				$action = $uri[1];
Tu peux avoir une erreur si tu n'as pas d'action dans l'url utilise ??

2020-01-15 12:11 UTC, fmoy commented on index.php
> +						$accueilController = new AccueilController;
C'est une syntaxe assez originale ... Instancier un objet c est pas tout à fait ça

2020-01-15 16:04 UTC, nicolasrll commented on index.php
> +				$action = $uri[1];
j'ai oublié d'adapter suite à mon dernier commit

2020-01-16 12:07 UTC, fmoy approved these changes

2020-01-16 12:07 UTC, merged