Step 7
nicolasrll/framework-from-scratch pull request #19
Opened 2020-01-20 19:23 UTC by nicolasrll

#18

2020-01-21 09:37 UTC, fmoy requested changes

2020-01-21 09:37 UTC, fmoy commented on Controllers/DefaultController.php
> +        $titlePage = $title;
prk créer une variable temporaire ?

2020-01-21 09:37 UTC, fmoy commented on accueil.php
> +<h1>Accueil</h1>
il y a pas de require template ?

2020-01-22 09:14 UTC, nicolasrll commented on accueil.php
> +<h1>Accueil</h1>
Non puisque je passe directement dans mon template.php.
C'est peut être une erreur de ma part mais dans le cas présent je voyait plus l'intérêt de passer par mes vues autre que template.php (en transmettant le titre en param à renderView()
Ma technique est limité selon le contenu à mettre dans mes page (si je l'envoi comme 2nd param)

2020-01-22 13:13 UTC, fmoy requested changes

2020-01-22 13:13 UTC, fmoy commented on Controller.php
> +<?php
c'est quoi ce fichier ?

2020-01-22 13:13 UTC, fmoy commented on accueil.php
> +<h1>Accueil</h1>
prk article.php il inclure un require ????

2020-01-22 13:13 UTC, fmoy commented on index.php
> +	if(isset($uri)){
c'est vraiment pas logique d'avoir autant de $uri sachant que tu l'as déclarée juste au dessus tu vas l'ecraser cmb de fois ?

2020-01-22 14:32 UTC, nicolasrll commented on accueil.php
> +<h1>Accueil</h1>
C'était un test que j'ai fais et j'ai oublié de nettoyer

2020-01-22 14:33 UTC, nicolasrll commented on Controller.php
> +<?php
Une erreur.. je sais pas pourquoi je l'ai toujours malgré mes rebase fait

2020-01-22 14:55 UTC, nicolasrll commented on Controller.php
> +<?php
Après avoir suppr le fichier j'ai fait un git add au lieu d'un git rm alors ça l'a réajouter...

2020-01-22 14:58 UTC, nicolasrll commented on Controller.php
> +<?php
C'est corrigé j'ai fait un nouveau commit et push

2020-01-23 18:10 UTC, fmoy approved these changes

2020-01-23 18:10 UTC, merged