Step 8
nicolasrll/framework-from-scratch pull request #23
Opened 2020-01-22 13:13 UTC by nicolasrll

#20

2020-01-22 13:21 UTC, fmoy requested changes

2020-01-22 13:21 UTC, fmoy commented on Controller.php
> +<?php
même remarque que la step 7 il fait quoi ce fichier ?

2020-01-22 13:21 UTC, fmoy commented on Controllers/AccueilController.php
> +    public function indexAction($loader)
????????????? depuis quand tu forces que chaque controller enfant déclare une variable sur toutes les méthodes qui utilise une vue ????????????? on est en poo ou pas ?

2020-01-22 13:21 UTC, fmoy commented on Controllers/DefaultController.php
> +    protected function renderView($title, $loader)
loader ?? tres significatif comme nom pour le templateRootDirectoryPath

2020-01-22 13:21 UTC, fmoy commented on index.php
> +<?php
et encore un chargement twig ? on le fait cmb de fois une dans renderView une dans index ?

2020-01-22 13:21 UTC, fmoy commented on views/article.php
> +    require 'template.php';
nan mais depuis quand on charge un fichier php avec twig ???

2020-01-23 13:59 UTC, nicolasrll commented on Controller.php
> +<?php
correction faite

2020-01-23 19:09 UTC, fmoy approved these changes

2020-01-23 19:09 UTC, merged